trigger:
- main
- beta

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '18.x'

- task: Npm@1
  inputs:
    command: 'install'
  displayName: "Install NPM Dependencies"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
  displayName: "Build"

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
  displayName: "Test"

- task: PublishTestResults@2
  condition: succeededOrFailed() # because otherwise we won't know what tests failed
  inputs:
    testResultsFiles: 'coverage/junit.xml'
  displayName: 'Publish npm test results to pipelines'

- task: PublishCodeCoverageResults@2
  displayName: "Publish code coverage results"
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: "coverage/cobertura-coverage.xml"